export const FETCH_BOOKS = "FETCH_BOOKS";
export const SELECT_BOOK = "SELECT_BOOK";
export const PURCHASE_BOOK = "PURCHASE_BOOK";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const CREATE_USER = "CREATE_USER";
export const CURRENT_USER_DETAILS = "CURRENT_USER_DETAILS";
export const FETCH_WRITERS = "FETCH_WRITERS";
export const SELECT_WRITER = "SELECT_WRITER";
